# Generated by Django 3.2.4 on 2021-06-14 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datanascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=13, null=True)),
                ('estadocivil', models.CharField(blank=True, choices=[('so', 'SOLTEIRO(A)'), ('ca', 'CASADO(A)'), ('se', 'SEPARADO(A)'), ('di', 'DIVORCIADO(A)'), ('vi', 'VIÚVO(A)')], default='so', max_length=2, null=True, verbose_name='Estado Civil')),
                ('necessidade', models.BooleanField(blank=True, default=False, null=True)),
                ('carteira', models.BooleanField(blank=True, default=False, null=True)),
                ('carteiracategoria', models.CharField(blank=True, choices=[('-', '--'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('ab', 'AB'), ('ac', 'AC'), ('ad', 'AD'), ('ae', 'AE')], default='-', max_length=2, null=True)),
                ('areainteresse', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
