# Generated by Django 3.2.4 on 2021-06-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadcurriculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='escolaridade',
            field=models.CharField(choices=[('fundai', 'Fundamental Incompleto'), ('fundac', 'Fundamental Completo'), ('medioi', 'Ensino Médio Completo'), ('medioc', 'Ensino Médio Incompleto'), ('superi', 'Superior Incompleto'), ('superc', 'Superior Completo'), ('posgra', 'Pós-Graduação')], default='fundai', max_length=6, verbose_name='Grau de escolaridade'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areainteresse',
            field=models.CharField(blank=True, choices=[('ad', 'ADMINISTRATIVA'), ('te', 'TÉCNICA'), ('cm', 'COMERCIAL'), ('tr', 'TRANSPORTES'), ('op', 'OPERACIONAL'), ('sg', 'SERVIÇOS GERAIS'), ('rh', 'RECURSOS HUMANOS'), ('pg', 'PROGRAMAÇÃO'), ('jn', 'JORNALÍSTICA')], max_length=2, null=True, verbose_name='Qual a área do seu interesse?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='carteira',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='carteiracategoria',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('ab', 'AB'), ('ac', 'AC'), ('ad', 'AD'), ('ae', 'AE')], max_length=2, null=True, verbose_name='Se sim, Qual a categoria?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='estadocivil',
            field=models.CharField(blank=True, choices=[('so', 'SOLTEIRO(A)'), ('ca', 'CASADO(A)'), ('se', 'SEPARADO(A)'), ('di', 'DIVORCIADO(A)'), ('vi', 'VIÚVO(A)')], max_length=2, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='necessidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
