# Generated by Django 3.2.4 on 2021-06-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadcurriculo', '0005_profile_aceitetermos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='necessidadecategoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
