# Generated by Django 3.2.4 on 2021-06-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadcurriculo', '0006_profile_necessidadecategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
